name: Create Certificate v2

on:
  workflow_dispatch:

jobs:
  create-certificate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Certificate v2
        run: |
          chmod +x ./create_certificate_v2.sh
          ./create_certificate_v1.sh \
            "${{ vars.LOGIN_URL }}" \
            "${{ vars.CERT_URL }}" \
            "${{ secrets.TRUSTOS_USERNAME }}" \
            "${{ secrets.TRUSTOS_PASSWORD }}" \
            "${{ github.actor }}" \
            "${{ github.sha }}" \
            "${{ github.repository }}"