name: Create TrustOS Certificate of a Commit

on:
  push:
    branches:
      - master
      - main
jobs:
  create-certificate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Certificate
        run: |
          chmod +x ./sh/trustos_cert_commit.sh
          ./sh/trustos_cert_commit.sh \
            "${{ vars.LOGIN_URL }}" \
            "${{ vars.CERT_URL }}" \
            "${{ secrets.TRUSTOS_USERNAME }}" \
            "${{ secrets.TRUSTOS_PASSWORD }}" \
            "${{ secrets.TRUSTOS_SECRET }}" \
            "${{ github.actor }}" \
            "${{ github.sha }}" \
            "${{ github.repository }}"
